version: "3"
services:
  cloudbeaver-prd:
    container_name: cloudbeaver-prd
    image: dbeaver/cloudbeaver:22.0.4
    networks:
      - web
    labels:
      - traefik.http.routers.cloudbeaver-prd.rule=Host(`db.energietransitiewindesheim.nl`)
      - traefik.http.routers.cloudbeaver-prd.tls=true
      - traefik.http.routers.cloudbeaver-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.cloudbeaver-prd.loadbalancer.server.port=8978
      - traefik.http.routers.cloudbeaver-prd.middlewares=private-network-ipwhitelist-cb
      - traefik.http.middlewares.private-network-ipwhitelist-cb.ipwhitelist.sourcerange= $IP_Whitelist
    volumes:
      - data:/opt/cloudbeaver/workspace
    restart: unless-stopped

networks:
  web:
    external: true
    
volumes:
  data: {}
