version: "3"
services:
  traefik-prd:
    container_name: traefik-prd
    image: traefik:v2.6.6
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - web
    volumes:
      - ../traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - .//acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always
networks:
  web:
    external:
      name: web
