version: "3"
services:
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: traefik:v2.6.6
    ports:
      - "${INTERMEDIATE_PORT}:443/tcp"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json # /opt/traefikc.acme.json needs to exist at Docker server
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:${INTERMEDIATE_PORT}"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.middlewares=traefik-ipwhitelist@file"
      - "--entrypoints.websecure.http.middlewares=simpleAuth@file"
    environment:
      - EMAIL=${EMAIL}
      - BASIC_AUTH_USERS=${BASIC_AUTH_USERS}
      - IP_WHITELIST=${IP_WHITELIST}
      - INTERMEDIATE_PORT=443    # Default port forwarded from router to Docker server

    labels:
      # Define router for Traefik dashboard accessible at <COMPOSE_PROJECT_NAME>.<DOMAIN>
      - traefik.http.routers.traefik.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=lets-encrypt
      - traefik.http.routers.traefik.service=api@internal


networks:
  web:
    external: true
