version: "3.8"
services:
  twomes-manual-server-tst:
    image: ghcr.io/energietransitie/needforheat-manual-server:main
    container_name: needforheat-manual-server-tst
    labels:
      - traefik.http.routers.needforheat-manual-server-tst.rule=Host(`manuals.tst.energietransitiewindesheim.nl`)
      - traefik.http.routers.needforheat-manual-server-tst.tls=true
      - traefik.http.routers.needforheat-manual-server-tst.tls.certresolver=lets-encrypt
      - traefik.http.services.needforheat-manual-server-tst.loadbalancer.server.port=8080
    networks:
      - web
    environment:
      - NFH_MANUAL_SOURCE=${NFH_MANUAL_SOURCE}
      - NFH_MANUAL_SOURCE_BRANCH=${NFH_MANUAL_SOURCE_BRANCH}
      - NFH_FALLBACK_LANG=${NFH_FALLBACK_LANG}
    restart: unless-stopped
    volumes:
      - source:/source

networks:
  web:
    external: true

volumes:
  source: {}
