version: "3.8"
services:
  needforheat-api-v2-prd:
    image: ghcr.io/energietransitie/twomes-backoffice-api:latest # Latest is always the latest stable version.
    container_name: needforheat-api-v2-prd
    labels:
      - traefik.http.routers.needforheat-api-v2-prd.rule=Host(`api.example.com`) && PathPrefix(`/v2`)
      - traefik.http.routers.needforheat-api-v2-prd.priority=20
      - traefik.http.middlewares.prod-stripprefix-v2.stripprefix.prefixes=/v2
      - traefik.http.routers.needforheat-api-v2-prd.tls=true
      - traefik.http.routers.needforheat-api-v2-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.needforheat-api-v2-prd.loadbalancer.server.port=8080
      - traefik.http.routers.needforheat-api-v2-prd.middlewares=prod-ratelimit,prod-stripprefix-v2
      - traefik.http.middlewares.prod-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.prod-ratelimit.ratelimit.burst=50
    networks:
      - web
    environment:
      - TWOMES_DSN=${TWOMES_DSN}
      - TWOMES_BASE_URL=${TWOMES_BASE_URL}
      - TWOMES_DOWNLOAD_TIME=${TWOMES_DOWNLOAD_TIME}
    restart: unless-stopped
    volumes:
      - data:/data

networks:
  web:
    external: true

volumes:
  data: {}
