version: "3.8"
services:
  needforheat-manual-server-prd:
    image: ghcr.io/energietransitie/needforheat-manual-server:latest # Latest is always the latest stable version.
    container_name: needforheat-manual-server-prd
    labels:
      - traefik.http.routers.needforheat-manual-server-prd.rule=Host(`manuals.energietransitiewindesheim.nl`)
      - traefik.http.routers.needforheat-manual-server-prd.tls=true
      - traefik.http.routers.needforheat-manual-server-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.needforheat-manual-server-prd.loadbalancer.server.port=8080
    networks:
      - web
    environment:
      - NFH_MANUAL_SOURCE=${NFH_MANUAL_SOURCE}
      - NFH_MANUAL_SOURCE_BRANCH=${NFH_MANUAL_SOURCE_BRANCH}
      - NFH_FALLBACK_LANG=${NFH_FALLBACK_LANG}
    restart: unless-stopped
    volumes:
      - source:/source

networks:
  web:
    external: true

volumes:
  source: {}
