version: "3"
services:
  portainer:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: portainer/portainer-ce:2.18.3
    networks:
      - web
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=lets-encrypt
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=9000
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=private-network-ipwhitelist-${COMPOSE_PROJECT_NAME}
      - traefik.http.middlewares.private-network-ipwhitelist-${COMPOSE_PROJECT_NAME}.ipwhitelist.sourcerange=$IP_Whitelist
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: unless-stopped
networks:
  web:
    external: true
    name: web
volumes:
  data: {}
