version: "3.8"
services:
  portainer-prd:
    container_name: ${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}
    image: portainer/portainer-ce:2.18.3
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}.tls.certresolver=lets-encrypt
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}.loadbalancer.server.port=9000
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}.middlewares=private-network-ipwhitelist-${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}
      - traefik.http.middlewares.private-network-ipwhitelist-${COMPOSE_PROJECT_NAME}-${SERVER_TYPE}.ipwhitelist.sourcerange=${IP_WHITELIST}
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always
networks:
  web:
    external: true
volumes:
  portainer_data:
    external: true
