version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.13.1
    networks:
      - web
    labels:
      - traefik.http.routers.portainer.rule=Host(`docker.energietransitiewindesheim.nl`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=lets-encrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.middlewares=private-network-ipwhitelist-port
      - traefik.http.middlewares.private-network-ipwhitelist-port.ipwhitelist.sourcerange= $IP_Whitelist 
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always
networks:
  web:
    external:
      name: web
volumes:
  data: {}
