version: "3"
services:
  mariadb_dev:
    container_name: mariadb_dev
    image: mariadb:10.7.3
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=twomes
    networks:
      - web
    volumes:
      - data:/var/lib/mysql
    restart: unless-stopped

networks:
  web:
    external: true

volumes:
  data: {}
