version: "3.8"
services:
  twomes-api-v2-tst:
    image: ghcr.io/energietransitie/twomes-backoffice-api:main
    container_name: twomes-api-v2-tst
    labels:
      - traefik.http.routers.twomes-api-v2-tst.rule=Host(`api.tst.energietransitiewindesheim.nl`) && Path(`/v2`)
      - traefik.http.middlewares.test-stripprefix-v2.stripprefix.prefixes=/v2
      - traefik.http.routers.twomes-api-v2-tst.tls=true
      - traefik.http.routers.twomes-api-v2-tst.tls.certresolver=lets-encrypt
      - traefik.http.services.twomes-api-v2-tst.loadbalancer.server.port=80
      - traefik.http.routers.twomes-api-v2-tst.middlewares=test-ratelimit,test-stripprefix-v2
      - traefik.http.middlewares.test-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.test-ratelimit.ratelimit.burst=50
    networks:
      - web
    environment:
      - TWOMES_DSN=${TWOMES_DSN}
    restart: unless-stopped
    volumes:
      - data:/data
networks:
  web:
    external:
      name: web
volumes:
  data: {}
